// <auto-generated />
using System;
using MER;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MER.Migrations
{
    [DbContext(typeof(MerContext))]
    partial class MerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MER.Beneficiario", b =>
                {
                    b.Property<int>("clienteCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("benefCartao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("benefCodigo")
                        .HasColumnType("int");

                    b.Property<string>("benefMatricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("benefNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clienteCNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clienteNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("planoCodigo")
                        .HasColumnType("int");

                    b.Property<string>("planoNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clienteCodigo");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("MER.Item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("produtoskuCodigo")
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<float>("taxaDesconto")
                        .HasColumnType("real");

                    b.Property<float>("taxaSubsidioCliente")
                        .HasColumnType("real");

                    b.Property<float>("taxaSubsidioEPH")
                        .HasColumnType("real");

                    b.Property<float>("valorCopay")
                        .HasColumnType("real");

                    b.Property<float>("valorDesconto")
                        .HasColumnType("real");

                    b.Property<float>("valorDescontoFolha")
                        .HasColumnType("real");

                    b.Property<float>("valorPMC")
                        .HasColumnType("real");

                    b.Property<float>("valorRepasse")
                        .HasColumnType("real");

                    b.Property<float>("valorSubsidioCliente")
                        .HasColumnType("real");

                    b.Property<float>("valorSubsidioEPH")
                        .HasColumnType("real");

                    b.Property<float>("valorVenda")
                        .HasColumnType("real");

                    b.HasKey("itemId");

                    b.HasIndex("produtoskuCodigo");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MER.Loja", b =>
                {
                    b.Property<int>("lojaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("lojaCNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lojaNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lojaUF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("redeCNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("redeCodigo")
                        .HasColumnType("int");

                    b.Property<string>("redeNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lojaCodigo");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("MER.Produto", b =>
                {
                    b.Property<int>("skuCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("adesao")
                        .HasColumnType("bit");

                    b.Property<string>("industriaNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("produtoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skuEAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skuNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("skuCodigo");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("MER.Venda", b =>
                {
                    b.Property<int>("codigoVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codigoNSU")
                        .HasColumnType("int");

                    b.Property<int>("codigoNSUOrigem")
                        .HasColumnType("int");

                    b.Property<int>("codigoOrigem")
                        .HasColumnType("int");

                    b.Property<string>("cupomFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataVenda")
                        .HasColumnType("datetime2");

                    b.Property<string>("prescritorNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prescritorNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prescritorTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prescritorUF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigoVenda");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("MER.Item", b =>
                {
                    b.HasOne("MER.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoskuCodigo");
                });
#pragma warning restore 612, 618
        }
    }
}
